title: Covid 19 for dummies - a knowledge base
description: Knowledge base on safety rules during the COVID-19 pandemic hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: pmarsceill/just-the-docs


logo: "images/Logo.png"

back_to_top: true
back_to_top_text: "Back to top"

